\documentclass[12pt]{article}

\input  4mbapreamble
\usepackage{cases}
\usepackage[makeroom]{cancel}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% FANCY HEADER AND FOOTER STUFF%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{fancyhdr,lastpage}
\pagestyle{fancy}
\fancyhf{}% clear all header and footer parameters
%%%\lhead{Student Name: \theblank{4cm}}
%%%\chead{}
%%%\rhead{Student Number: \theblank{3cm}}
%%%\lfoot{\small\bfseries\ifnum\thepage<\pageref{LastPage}{CONTINUED\\on next page}\else{LAST PAGE}\fi}
\lfoot{}
\cfoot{{\small\bfseries Page \thepage\ of \pageref{LastPage}}}
\rfoot{}
\renewcommand\headrulewidth{0pt}% Removes funny header line
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

<<global_options,include=FALSE>>=
opts_chunk$set(external=FALSE)
@
d
<<pre_load,include=FALSE>>=
options(tikzDefaultEngine='pdftex')
@

\begin{center}
{\bf Mathematics 4MB3/6MB3 Mathematical Biology\\
\smallskip
2017 ASSIGNMENT 3}\\
\medskip
\underline{\emph{Group Name}}: \texttt{{\color{blue}Model Students}}\\
\medskip
\underline{\emph{Group Members}}: {\color{blue}Nicole Dumont, Melody Fong, Connor LeDrew, Carolina Weishaar}
\end{center}

\bigskip
\noindent
This assignment was {\bfseries\color{black} due in class} on \textcolor{black}{\bf Wednesday 1 March 2017 at 11:30am}.

\section*{Analysis of the standard SIR model with vital dynamics}

Consider the standard SIR model with vital dynamics,
\begin{subequations}\label{E:SIR}
\begin{align}
 \frac{dS}{dt} &= \mu N - \frac{\beta}{N} SI - \mu S\\
  \noalign{\vspace{8pt}}
  \frac{dI}{dt} &= \frac{\beta}{N} SI - \gamma I - \mu I\\
  \noalign{\vspace{8pt}}
  \frac{dR}{dt} &= \gamma I - \mu R
\end{align}
\end{subequations}
where $S$, $I$ and $R$ denote the numbers of susceptible, infectious
and removed individuals, respectively, and $N=S+I+R$ is the total
population size. The \emph{per capita} rates of birth and death are
the same (both are equal to $\mu$). As usual, $\beta$ is the
transmission rate and $\gamma$ is the recovery rate.

\begin{enumerate}[(a)]

\item Prove that the population size $N$ is constant and that
  equations \eqref{E:SIR} are biologically well-defined, \ie the set
  $\Delta$ of biologically meaningful states is forward-invariant.
  (Note that you will need to begin by defining precisely the set
  $\Delta$ and the term ``forward-invariant''.)

{\color{blue}
\begin{proof}
{\color{magenta}
\begin{align}
N &= S + I + R \\
\frac{dN}{dt} &= \frac{dS}{dt} + \frac{dI}{dt} + \frac{dR}{dt} \\
&= \mu N - \frac{\beta}{N} SI - \mu S + \frac{\beta}{N} - \gamma I - \mu I + \gamma I - \mu R \\
&= \mu (N - S - I - R) \\
&= 0
\end{align}
$\therefore$ N is constant $\forall$ t. \\
The set of biologically meaningful states is
\begin{equation}
  \Delta = \{ (S,I,R) : 0 \leq S,I,R \leq N\}.
\end{equation}
A set $S$ is forward invariant if $x(t_0) \in S \Rightarrow x(t) \in S \quad \forall t>0$. Consider the behaviour of $(S,I,R)$ at $0$ and $N$:
\begin{align}
  S &= 0 \rightarrow \dot{S}=\mu N \geq 0   \nonumber \\
  & \quad \Rightarrow S(0) \geq 0 \rightarrow S(t) \geq 0 \quad \forall t>0 \\
  I &= 0 \rightarrow \dot{I}= 0  \nonumber \\
  & \quad \Rightarrow I(0) \geq 0 \rightarrow I(t) \geq 0 \quad \forall t>0 \\
  R &= 0 \rightarrow \dot{R}=\gamma I \geq 0  \nonumber \\
  & \quad \Rightarrow R(0) \geq 0 \rightarrow R(t) \geq 0 \quad \forall t>0 \\
  S &= N \rightarrow \dot{S}=-\beta I = 0  \nonumber \\
  & \quad \Rightarrow S(0) \leq N \rightarrow S(t) \leq N \quad \forall t>0 \\
  I &= N \rightarrow \dot{I}=-(\gamma + \mu) N \leq 0  \nonumber \\
  & \quad \Rightarrow I(0) \leq N \rightarrow I(t) \leq N \quad \forall t>0 \\
  R &= N \rightarrow \dot{R}=-\mu N \leq 0  \nonumber \\
  & \quad \Rightarrow R(0) \leq N \rightarrow R(t) \leq N \quad \forall t>0 
\end{align}
Thus, $(S(0), I(0), R(0)) \in \Delta \Rightarrow (S(t), I(t), R(t)) \in \Delta \quad \forall t>0$ and $\Delta$ is a forward invariant set.

}
\end{proof}
}

\item Show that equations \eqref{E:SIR} are equivalent dynamically to
 equations for the proportions (rather than numbers) of individuals
  in each disease state. For the remainder of this problem, use the
  equations in proportional form.

{\color{blue}
\begin{proof}
{\color{magenta}

\begin{subnumcases} {F(t) = \label{E:SIR/N}} 
\frac{d}{dt}\frac{S}{N} = \frac{d\tilde{S}}{dt} &= $\mu\frac{N}{N} - \beta\frac{SI}{N^2} - \mu\frac{S}{N}$ \label{E:SIR/N a} \\
&= $\mu\tilde{N} - \beta\tilde{S}\tilde{I} - \mu\tilde{S}$ \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d}{dt}\frac{I}{N} = \frac{d\tilde{I}}{dt} &= $\beta \frac{SI}{N^2} - \gamma\frac{I}{N} - \mu\frac{I}{N}$ \label{E:SIR/N b} \\
&= $\beta\tilde{S}\tilde{I} - \gamma\tilde{I} - \mu\tilde{I}$ \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d}{dt}\frac{R}{N} = \frac{d\tilde{R}}{dt} &= $\gamma \frac{I}{N} - \mu\frac{R}{N}$ \label{E:SIR/N c} \\
&= $\gamma\tilde{I} - \mu\tilde{R}$ \nonumber
\end{subnumcases} 
$\therefore$ the equations for the proportions \ref{E:SIR/N} (denoted by $\sim$) are dynamically equivalent to \eqref{E:SIR}.
}
\end{proof}
}

\item Re-express the equations for proportions in \emph{dimensionless}
  form using the dimensionless time coordinate
  \begin{subequations}\label{E:dimparms}
    \begin{equation}
      \tau=(\gamma+\mu)t\,,
    \end{equation}
  and the dimensionless parameters
  \begin{align}
    \R_0 &= \frac{\beta}{\gamma+\mu} \,,\\
    \noalign{\vspace{5pt}}
    \eps &= \frac {\mu}{\gamma+\mu} \,.
  \end{align}
\end{subequations}
What are the biological meanings of $\tau$, $\R_0$ and $\eps$? Why are
they good choices for non-dimensionalizing the equations? For a few
diseases that you are familiar with, what is the order of magnitude of
$\eps$?

{\color{blue}
\begin{proof}
{\color{magenta}
\emph{Note:} $\frac{d\tau}{dt}=(\gamma + \mu)$ \\
\noindent
\begin{minipage}[b]{0.75\textwidth}
\begin{flushleft}
\begin{subnumcases}{F(\tau) =}
\frac{d\tilde{S}}{dt}\frac{d\tau}{dt} = \frac{d\tilde{S}}{d\tau} &= $(\mu\tilde{N} - \beta\tilde{S} \tilde{I} - \mu\tilde{S})(\frac{1}{\gamma + \mu})$ \label{E:dimlessSIR/N a}\\
&= $\epsilon\tilde{N} - \R_0\tilde{S}\tilde{I} - \epsilon\tilde{S}$ \nonumber \\
&= $\epsilon(\tilde{N}-\tilde{S}) - \R_0\tilde{S}\tilde{I}$ \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d\tilde{I}}{dt}\frac{d\tau}{dt} = \frac{d\tilde{I}}{d\tau} &= $(\beta\tilde{S}\tilde{I} - \gamma\tilde{I} - \mu\tilde{I})(\frac{1}{\gamma + \mu})$ \label{dimlessSIR/N b}\\
&= $\R_0\tilde{S}\tilde{I} - \tilde{I}(\frac{\gamma + \mu}{\gamma + \mu})$ \nonumber \\
&= $\R_0\tilde{S}\tilde{I} - \tilde{I}$ \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d\tilde{R}}{dt}\frac{d\tau}{dt} = \frac{d\tilde{R}}{d\tau} &= $(\gamma\tilde{I} - \mu\tilde{R})(\frac{1}{\gamma + \mu})$ \label{E:dimlessSIR/N c}\\
&= $(\gamma\tilde{I} - \mu(\tilde{N} - \tilde{S} - \tilde{I}))(\frac{1}{\gamma + \mu})$ \nonumber \\
&= $(\tilde{I}(\gamma + \mu) - \mu\tilde{N} + \mu\tilde{S})(\frac{1}{\gamma + \mu})$ \nonumber \\
&= $\tilde{I} - \epsilon\tilde{N} + \epsilon\tilde{S}$ \nonumber \\
&= $\tilde{I} - \epsilon(\tilde{N} - \tilde{S})$ \nonumber 
\end{subnumcases}
\end{flushleft}
\end{minipage}
\fbox{
\begin{minipage}{0.2\textwidth} 
\emph{Note:}
\begin{align*}
\tilde{N} &= \tilde{S} + \tilde{I} + \tilde{R} \\
&= \frac{S + I + R}{N} \\
&= \frac{N}{N} = 1
\end{align*}
\end{minipage}
}
$\tau$ is the number of individuals leaving the system due to recovery or death. \\
$\R_0$ is the basic reproduction number, the number of new transmissions per infected individual. \\
$\epsilon$ is the number of new individuals entering the system per infected individual leaving.
}
\end{proof}
}

\item Show that there are exactly two equilibria: the disease free
  equilibrium (DFE) at $(S,I)=(1,0)$ and an endemic equilibrium (EE)
  at $(S,I)=(\Shat,\Ihat)$, where $\Shat$ and $\Ihat$ can be expressed
  compactly in terms of $\R_0$ and $\eps$.  Are both equilibria always
  biologically relevant?

{\color{blue}
\begin{proof}
{\color{magenta}
Notice that $\frac{d\tilde{R}}{d\tau}$ is a linear combination of $\tilde{S}$ and $\tilde{I}$, independent of $\tilde{R}$, so $F(\tau) = F(\tilde{S}(\tau),\tilde{I}(\tau))$. \\

For the DFE,
\begin{subnumcases}{F(1,0) = \label{E:DFE}}
\frac{d\tilde{S}}{d\tau} &= $\epsilon(\tilde{N} - \tilde{S}) - \R_0\tilde{S}\tilde{I}$ \label{E:DFE a} \\
&= 0 \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d\tilde{I}}{d\tau} &= $\R_0\tilde{S}\tilde{I} - \tilde{I}$ \label{E:DFE b} \\
&= 0 \nonumber 
\end{subnumcases}
thus proving that $(\tilde{S},\tilde{I}) = (1,0)$ is an equilibrium state for the system. \\

\begin{subnumcases}{F(\Shat,\Ihat) = \label{E:EE}}
\frac{d\tilde{S}}{d\tau} &= $\epsilon(\tilde{N} - \tilde{S}) - \R_0\tilde{S}\tilde{I} = 0$ \label{E:EE a} \\
\epsilon(\tilde{N} - \tilde{S}) &= $\R_0\tilde{S}\tilde{I}$ \nonumber \\
\Ihat &= $\frac{\epsilon(1 - \Shat)}{\R_0\Shat}$ \nonumber \\
&= $\epsilon(1 - \frac{1}{\R_0})$ \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d\tilde{I}}{d\tau} &= $\R_0\tilde{S}\tilde{I} - \tilde{I} = 0$ \label{E:EE b} \\
\tilde{I} &= $\R_0\tilde{S}\tilde{I}$ \nonumber \\
\Shat &= $\frac{1}{R_0}$ \nonumber
\end{subnumcases}
Whereas for the EE, when $(\tilde{S},\tilde{I}) = (\Shat,\Ihat) = (\frac{1}{\R_0},\epsilon(1 - \frac{1}{\R_0}))$, this is an equilibrium state for the system. \\

The DFE is always biologically relevant as the proportions for susceptibles and infecteds ($\tilde{S}$ and $\tilde{I}$) at the equilibrium (1,0) is strictly bound within [0,1] for all time. The EE is only biologically relevant when $\R_0>1$ and $0\leq\epsilon\leq\frac{\R_0}{\R_0-1}$, bounding both $\Shat=\frac{1}{\R_0}$ and $\Ihat=\epsilon(1-\frac{1}{\R_0})$ between [0,1] for all time.
}
\end{proof}
}

\item Show that the DFE is locally asymptotically stable (LAS) if
  $\R_0<1$ and the EE is LAS if $\R_0>1$.

{\color{blue}
\begin{proof}
{\color{magenta}
The linearization of this systems of nonlinear differential equations about the equilibrium $(S^*, I^*)$ is given by its Jacobian matrix evaluated at an equilibrium point of the system is 
\begin{align}
J &= \left [ \begin{matrix}
 	\frac{\partial}{\partial S^*} \left ( \frac{dS^*}{d\tau} \right ) & \frac{\partial}{\partial I^*}\left ( \frac{dS^*}{d\tau} \right ) \\
	\frac{\partial}{\partial S^*}\left ( \frac{dI^*}{d\tau} \right ) & \frac{\partial}{\partial I^*}\left ( \frac{dI^*}{d\tau} \right )
\end{matrix} \right ] \\
&= \left [ \begin{matrix}
 	-\R_0 I^* - \epsilon & -\R_0 S^* \\
	\R_0 I^* & \R_0 S^* - 1
\end{matrix} \right ] 
\end{align}

It's eigenvalues can be found by solving its characteristic polynomial.
\begin{equation}
\det(J- \lambda I)  = \lambda^2 + (1+\epsilon +\R_0 I^* - \R_0 S^*)\lambda + \epsilon - \epsilon \R_0 S^* + \R_0 I^* = 0
\end{equation}

The equilibrium $(S^*, I^*)$ is asymptotically stable if all of the eigenvalues of the linearized system at $(S^*, I^*)$ have negative real parts. 

For the DFE $(S^*, I^*)=(1,0)$ and the characteristic polynomial is
\begin{align}
 0 &= \lambda^2 + (1 - \R_0)\lambda + \epsilon(1 - \R_0) \\
 &= (\lambda + 1 - \R_0)(\lambda + \epsilon)
\end{align}
so the eigenvalues are $-\epsilon, \R_0 - 1$. These are both negative, and therefore the DFE is asymptotically stable, if $\R_0 <1 $.

For the EE $(S^*, I^*)=\left (\frac{1}{\R_0}, \frac{\epsilon}{\R_0}(\R_0 - 1) \right )$ and the characteristic polynomial is
\begin{equation}
	0 = \lambda^2 + \epsilon \R_0 \lambda + \epsilon(\R_0 -1) 
\end{equation}
which has solutions $\lambda_\pm = -\frac{\epsilon \R_0}{2} \pm \frac{1}{2} \sqrt{\epsilon^2\R_0^2 - 4\epsilon(\R_0 - 1)} $. The eigenvalues are negative if
\begin{align}
	0 >& -\epsilon \R_0 + \sqrt{\epsilon^2\R_0^2 - 4\epsilon(\R_0 - 1)}  \\
	\cancel{\epsilon^2 \R_0^2} >& \cancel{\epsilon^2\R_0^2} - 4\epsilon(\R_0 - 1) \\
	\R_0 > 1
\end{align}
Thus, the EE is asymptotically stable if $\R_0 > 1 $.

}
\end{proof}
}

\item Prove that the DFE is, in fact, globally asymptotically stable (GAS) if $\R_0\le1$.  \emph{\underline{Hint}:} This requires some careful analysis.  Begin by using the function $L(S,I)=I$, and Theorem~2 stated in Assignment 1 under ``Notes on Lyapunov Functions'', to prove that all initial states in $\Delta$ are attracted to the $S$ axis.
  \label{DFEGASprob}

{\color{blue}
\begin{proof}
{\color{magenta}
Consider the function $L:\Delta \rightarrow \R$ defined as $L(S,I)=I$. Let $\mathcal{C}=\{(S,I) \in \Delta : I=0, S \ne \frac{1}{\R_0} \}$.
\begin{align}
  L(S,I) &= I=0 \quad \forall (S,I) \in \mathcal{C} \\
  L(S,I) &= I>0 \quad \forall (S,I) \in \Delta \setminus \mathcal{C} \\
  \dot{L}(S,I) &= \underbrace{(\R_0 S - 1)}_{<0 \ if \ \R_0 \leq 1}\underbrace{I}_{>0} <0 \quad \forall (S,I) \in \Delta \setminus \mathcal{C}
\end{align}
Thus, L is a strict Lyapunov function and $\mathcal{C}$ is globally asymptotically stable if $\R_0 \leq 1$. All initial states in $\mathcal{B} \equiv \Delta \setminus \{(S,I): S = \frac{1}{\R_0}  \}$ (an open, dense subset of $\Delta$) are attracted to the DFE when $\R_0 \leq 1$. $\mathcal{B}$ is the basin of attraction of the DFE. 

This result makes biological sense. If $\R_0 \leq 1$, then the expected number of secondary cases produced by a single primary case (in a completely susceptible population) is less than or equal to one. Clearly, not enough new infecteds will be created to sustain an epidemic. 
}
\end{proof}
}

\item Prove that the EE is GAS if $\R_0>1$. \quad\emph{\underline{Hint}:} Consider
\begin{equation}\label{E:LyapFun}
L(S,I) = S - \Shat\log{S} + I - \Ihat\log{I} \,,
\end{equation}
and convince yourself that condition (a) in Theorem~1 stated in Assignment 1 under ``Notes on Lyapunov Functions'' can be replaced with
\begin{equation}\label{E:}
L(X)>L(X_*) \quad \text{for all} \quad X\in\openset\setminus\{X_*\} \,.
\end{equation}
\emph{\underline{Note}:} By GAS we mean here that \emph{almost all} initial states are attracted to the EE.  One way of making this precise is to say that the \emph{basin of attraction} of the EE is an open, dense subset of $\Delta$.  You should completely describe the basins of attraction of both the EE and the DFE.  Do your results make biological sense?
  \label{EEGASprob}

{\color{blue}
\begin{proof}
{\color{magenta}
\begin{align}
  \frac{\partial L}{\partial S} &= 1 - \frac{\Shat}{S} = 0 \quad \text{when} \quad S=\Shat \\ 
  \frac{\partial L}{\partial I} &= 1 - \frac{\Ihat}{I} = 0 \quad \text{when} \quad I=\Ihat 
\end{align}
$(\Shat,\Ihat)$ is a stationary point of $L(S,I)$. 
\begin{align}
  \frac{\partial^2 L}{\partial S^2} &= 1 + \frac{\Shat}{S^2}  \\ 
  \frac{\partial^2 L}{\partial I^2} &= 1 + \frac{\Ihat}{I^2} \\
  \frac{\partial^2 L}{\partial I \partial S} &= 0
\end{align}
Since
\begin{equation}
  \frac{\partial^2 L}{\partial S^2} \biggr |_{(\Shat,\Ihat)} \frac{\partial^2 L}{\partial I^2}\biggr |_{(\Shat,\Ihat)} - \frac{\partial^2 L}{\partial I \partial S}\biggr |_{(\Shat,\Ihat)} = \left (1 + \frac{1}{\Shat} \right )\left (1 + \frac{1}{\Ihat} \right ) >0
\end{equation}
$(\Shat,\Ihat)$ is a minimum or maximum point and not a saddle point. And since
\begin{equation}
  \frac{\partial^2 L}{\partial S^2} \biggr |_{(\Shat,\Ihat)} >0, \quad \quad \frac{\partial^2 L}{\partial I^2}\biggr |_{(\Shat,\Ihat)} >0 
\end{equation}
$(\Shat,\Ihat)$ is a minimum of $L(S,I)$ and thus
\begin{equation}
L(S,I)>L(\Shat,\Ihat) \quad \forall  (S,I)\in\openset\setminus\{(\Shat,\Ihat)\}.
\end{equation}
where $\openset= \Delta \setminus \{ (S,I) \in \Delta: S,I \neq 0 \}$ (since $L(S,I)$ is not defined on $S=0$ or $I=0$). Note that $\openset$ is an open, dense subset of $\Delta$.
\begin{align}
  \dot{L}(S,I) &= \frac{dS}{d\tau} - \frac{\Shat}{S}\frac{dS}{d\tau} + \frac{dI}{d\tau} - \frac{\Ihat}{I}\frac{dI}{d\tau} \\
  &= \epsilon - (\R_0 I + \epsilon)S - \frac{1}{\R_0 S}(\epsilon - (\R_0 I +\epsilon)S) + (\R_0 S -1)I - \frac{\epsilon}{\R_0}(\R_0 S -1) \\
  &= -\frac{\epsilon}{\R_0}(\R_0 S -1)^2 \\
  &<0
\end{align}
Thus, $L(S,I)$ is a Lyapunov function and the EE is GAS. The basin of attraction of the EE is $\openset$.
}
\end{proof}
}

\item Prove that the approach to the EE occurs via damped oscillations
  if and only if $\eps<\eps^*$, where
\begin{equation}\label{E:Gstar}
\eps^* = \frac {4(\R_0-1)}{\R_0^2} \,.
\end{equation}
For which diseases that you are familiar with would you expect damped
oscillations versus monotonic convergence to the equilibrium?

{\color{blue}
\begin{proof}
{\color{magenta}
The approach to the EE occurs via damped oscillations if and only if the linearized system about the EE has complex conjugate eigenvalues with negative real parts. This is because the general solution of the linearized system, with eigenvalues $\lambda_\pm = \alpha \pm i\beta$, is
\begin{equation}
\begin{cases}
  S(\tau) = A_+ e^{\alpha \tau}\cos{\beta \tau} + A_- e^{\alpha \tau}\sin{\beta \tau} \\
  I(\tau) = B_+ e^{\alpha \tau}\cos{\beta \tau} + B_- e^{\alpha \tau}\sin{\beta \tau}
\end{cases}
\end{equation}
The cosine and sine terms result in oscillations around the equilibrium. If $\alpha < 0$, the expontential terms cause decay and the oscillations are damped.
The eigenvales of the linearized system about the EE are $\lambda_\pm = -\frac{\epsilon \R_0}{2} \pm \frac{1}{2} \sqrt{\epsilon^2\R_0^2 - 4\epsilon(\R_0 - 1)} $. These are complex conjugate when
\begin{align}
0 &> \epsilon^2\R_0^2 - 4\epsilon(\R_0 - 1) \\
\epsilon &< \frac{4(\R_0 - 1)}{\R_0^2} \equiv \epsilon^*
\end{align}
The real part, $-\frac{\epsilon \R_0}{2}$ is always negative. Thus, the approach to the EE occurs via damped oscillations.
**ANSWER SECOND PART
}
\end{proof}
}

\item For $\eps<\eps^*$, derive expressions for the period of damped
  oscillations onto the EE and the $e$-folding time for decay of the
  amplitude of oscillation.  Use \Rlogo to make a plot that
  displays your results graphically for some biologically relevant and
  illustrative parameter values.

{\color{blue}
\begin{proof}[Solution]
{\color{magenta}
The oscillations are due to the cosine and sine terms in the solution of the linearized system about the EE. Thus, the period of oscillations is given by the period of the trigonometric terms, $\frac{2\pi}{\beta}$. For the EE it is
\begin{equation}
    \frac{4\pi}{ \sqrt{4\epsilon(\R_0 - 1) - \epsilon^2\R_0^2 }} .
\end{equation}
The decay of the oscillations is due to the expontential term in the solution of the linearized system about the EE. The $e$-folding time of the decay is $\frac{-1}{\alpha}$. For the EE it is
\begin{equation} \label{e-folding}
    \frac{2}{\epsilon \R_0}.
\end{equation}
}
<<period,fig.height=6,dev="tikz">>=
R0 <- seq(1,20,length=60)
eps <- seq(0.01,0.9,length=60)

#Defining functions thats calculates the period
period <- function(eps, R0) {
  (4*pi)/sqrt(4*eps*(R0-1)-(R0*eps)^2)
}
#Matrix of period values for all combinations of values of R0, epsilon
periodmatrix <- outer(eps,R0,period)
#Setting NaNs and complex numbers to 0
periodmatrix[is.na(periodmatrix)] <- 0
periodmatrix[is.complex(periodmatrix)] <- 0

#3D plot of period vs R0 and epsilon
persp(eps, R0, periodmatrix, theta = 30, phi = 30, expand = 0.5, 
      col = "lightblue",ltheta = 120, shade = 0.75, 
      ticktype = "detailed", xlab = "$\\epsilon $", 
      ylab = "$\\R_0$", zlab = "Period") -> res

#Showing epsilon^*
epsstar <- 4*(R0-1)/R0^2 
lines (trans3d(epsstar, R0, rep(0,60), pmat = res), col = 4)
mtext("$\\epsilon^*(\\R_0)$", side=4, line=-6, padj=17, las=2, col=4)

title(main = "Period of Damped Oscillations") 
@ 

<<efolding,fig.height=6,dev="tikz">>=
R0 <- seq(1,20,length=60)
eps <- seq(0.1,0.9,length=60)

#Defining functions thats calculates the e-folding time
efold <- function(R0, eps) {
    2/(R0*eps)
}
#Matrix of e-fold values for all combinations of values of R0, epsilon
efoldmatrix <- outer(eps,R0,efold)
#Setting NaNs and complex numbers to 0
efoldmatrix[is.na(efoldmatrix)] <- 0
efoldmatrix[is.complex(efoldmatrix)] <- 0

#3D plot of e-folding time vs R0 and epsilon
persp(eps, R0, efoldmatrix, theta = 30, phi = 30, expand = 0.5, 
      col = "lightblue",ltheta = 120, shade = 0.75, 
      ticktype = "detailed", xlab = "$\\epsilon $", 
      ylab = "$\\R_0$", zlab = "e-Folding Time") -> res

#Showing epsilon^*
epsstar <- 4*(R0-1)/R0^2 
lines (trans3d(epsstar, R0, rep(0,60), pmat = res), col = 4)
mtext("$\\epsilon^*(\\R_0)$", side=4, line=-6, padj=17, las=2, col=4)

title(main = "e-Folding Time of Damped Oscillations") 
@ 
\end{proof}
}

\item Prove that as $\R_0$ is increased from $0$ to $\infty$, three
  ``bifurcations'' occur.  In addition, use \Rlogo to make a
  four-panel plot that illustrates the different dynamics (phase
  portraits) in each of the four $\R_0$ intervals that have distinct
  dynamics. (\emph{\underline{Hint}:} I suggest you choose $\eps=8/9$ for this
  figure, but you should explain why this is a good choice.)

  \smallskip

  Note that ``bifurcation'' is in quotes above because many dynamicists
  would consider only one of the three transitions to be a genuine
  bifurcation (it happens to be a \emph{transcritical bifurcation}).
  The other two dynamical transitions yield biologically relevant
  qualitative changes, but the phase portraits on either side of the
  ``bifurcation point'' are actually topologically conjugate.

{\color{blue}
\begin{proof}
{\color{magenta}
If we set $R_0 = 0$, 

\begin{subnumcases}{F(\tilde(S),\tilde(I)) = \label{E:EE}}
\frac{d\tilde{S}}{d\tau} &= $\epsilon(\tilde{N} - \tilde{S}) = 0$ \label{E:EE a} \\
\tilde{S} &= $\tilde{N} = 1$ \nonumber \\
\noalign{\vspace{8pt}} \nonumber \\
\frac{d\tilde{I}}{d\tau} &= $- \tilde{I} = 0$ \label{E:EE b} \\
\end{subnumcases}

As a result, in this case there exists only a single fixed point when $R_0$ and based on the matrix derived in question e, we know that it is asymptotically stable.

When $ 0 < R_0 < 1$,
Use the results from the questions above 

When $R_0 = 1$,
derive it 

When $R_0 > 1$
Use the results from the questions above
<<bifur,fig.height=6,dev="tikz",external=FALSE>>=
library(deSolve)

SIR.vector.field <- function (t, vars, pars = c(eps,R_0)) {
  with(as.list(c(vars, pars)), {
    dI = R_0*S*I/N - I
    dS = eps - R_0*S*I - eps*S
    vec.fld <- c(dI=dI, dS=dS)
    return(list(c(vec.fld)))
  })
}

draw.soln <- function(ic=c(x=1,y=0),tmax=1,
                      times=seq(0,tmax,by=tmax/500),
                      func,parms,...) {
  soln <- ode(ic,times,func,parms)
  lines(times,soln[,"y"],lwd=2,...)
}

## Plot Solutions of the SIR Model
## draw box for plot
plot(0,0,xlim=c(0,1),ylim=c(0,1),type="n",
     xlab="Susceptibility (S)",ylab="Prevalence (I)",
     las=1)

## draw solutions for several values of parameter R_0
vals <- c(0,1/2, 1,8)
line <- c(1:length(vals))
for (i in 1:length(vals)) {
  draw.soln(x=S,y=I,func=SIR.vector.field,
            parms=c(eps = (8/9), R_0=vals[i]),
            lty=line[i], ## use a different line style for each solution
            col=line[i]) ## use a different line colour for each solution
}
## draw legend for different values of R_0
legend("topright",legend=vals,lty=line,col=line,title="$\\R_0$ Values")
@

}
\end{proof}
}

\item Are there real diseases that display recurrent epidemics for which the standard SIR model that you have studied in this problem might be adequate to explain the observed epidemic dynamics?  If so, which diseases?  If not, why not?

{\color{blue}
\begin{proof}
{\color{magenta} The SIR model cannot explain recurrence, which is a inherent quality of epidemics, so it cannot accurately model real diseases as observed. As shown in part (i), the period of oscillations for the SIR model are damped and show an eventual exponential decline to the EE for increasing $\R_0$ and $\epsilon$ values with sharp peaks of varied amplitude along the curve of points of $\epsilon^(\R_0)$. However, the $e$-folding time of each peak has a rate of decay given by \eqref{e-folding}, and, as shown in the figure, smoothly decays to the EE for all values of $\R_0$ and $\epsilon$.
}
\end{proof}
}

\end{enumerate}

%%\newpage
\bibliographystyle{vancouver}
%%\bibliography{DavidEarn,MyPubs}

\bigskip\vfill

\centerline{\bf--- END OF ASSIGNMENT ---}

\bigskip
Compile time for this document:
\today\ @ \thistime

\end{document}
